# Generated by Django 5.0.2 on 2024-08-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_password_admin_register_a_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_register',
            old_name='A_password',
            new_name='a_password',
        ),
        migrations.RenameField(
            model_name='admin_register',
            old_name='A_username',
            new_name='a_username',
        ),
    ]
