# Generated by Django 5.0.2 on 2024-08-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0002_alter_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_shape', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category')),
                ('category_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category_shape')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category_type')),
            ],
        ),
    ]
