# Generated by Django 5.0.2 on 2024-08-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0004_image_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icons_app.image_plan'),
        ),
    ]
