# Generated by Django 5.0.2 on 2024-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0006_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='register',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
