# Generated by Django 5.0.2 on 2024-08-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0007_register_reset_token_register_reset_token_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category_shape',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_plan',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category_Shape',
        ),
        migrations.DeleteModel(
            name='Category_Type',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='image_plan',
        ),
    ]
