# Generated by Django 5.0.2 on 2024-08-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0008_remove_image_category_remove_image_category_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35)),
                ('cat_image', models.ImageField(upload_to='cat_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_shape', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='gradient_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='image_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_plan', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='sub_gradient_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_gradient_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_amt', models.IntegerField()),
                ('plan_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category')),
                ('category_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category_shape')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.category_type')),
                ('image_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.image_plan')),
            ],
        ),
        migrations.CreateModel(
            name='request_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('rq_image', models.ImageField(upload_to='re_images/')),
                ('gradient_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.gradient_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.register')),
            ],
        ),
        migrations.CreateModel(
            name='gradient_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_image', models.ImageField(upload_to='gradient_images/')),
                ('gradient_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.gradient_category')),
                ('sub_gradient_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.sub_gradient_category')),
            ],
        ),
    ]
