# Generated by Django 5.0.2 on 2024-08-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0009_category_category_shape_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradient_image',
            name='gradient_category',
        ),
        migrations.AddField(
            model_name='sub_gradient_category',
            name='gradient_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icons_app.gradient_category'),
        ),
    ]
