# Generated by Django 5.0.2 on 2024-08-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0010_remove_gradient_image_gradient_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request_quote',
        ),
    ]
