# Generated by Django 5.0.2 on 2024-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0012_request_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_quote',
            name='gradient_category',
        ),
        migrations.AddField(
            model_name='request_quote',
            name='service',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
