# Generated by Django 5.0.2 on 2024-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0013_remove_request_quote_gradient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=25),
        ),
    ]
