# Generated by Django 5.0.2 on 2024-08-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0014_alter_image_image_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_plan',
        ),
    ]
