# Generated by Django 5.0.2 on 2024-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0015_delete_image_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_gradient_category',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='featured_images/'),
        ),
    ]
