# Generated by Django 5.0.2 on 2024-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0016_sub_gradient_category_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_gradient_category',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='sub_gradient_category',
            name='f_image',
            field=models.ImageField(null=True, upload_to='f_images/'),
        ),
    ]
