# Generated by Django 5.0.2 on 2024-08-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0018_alter_sub_gradient_category_f_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_gradient_category',
            name='f_image',
        ),
    ]
