# Generated by Django 5.0.2 on 2024-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0019_remove_sub_gradient_category_f_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_gradient_category',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_gradient_images/'),
        ),
    ]
