# Generated by Django 5.0.2 on 2024-08-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0021_subscriptionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
