# Generated by Django 5.0.2 on 2024-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0023_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
