# Generated by Django 5.0.2 on 2024-08-26 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0025_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.FileField(upload_to='cat_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 10, 40, 41, 437889, tzinfo=datetime.timezone.utc)),
        ),
    ]
