# Generated by Django 5.0.2 on 2024-08-26 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0026_alter_category_cat_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 17, 25, 5, 833322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(auto_now_add=True)),
                ('sub_gradient_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.sub_gradient_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons_app.register')),
            ],
            options={
                'unique_together': {('user', 'sub_gradient_category')},
            },
        ),
    ]
