# Generated by Django 5.0.2 on 2024-08-27 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0027_alter_subscription_expiry_date_pagelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], max_length=25),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 5, 30, 10, 854692, tzinfo=datetime.timezone.utc)),
        ),
    ]
