# Generated by Django 5.0.2 on 2024-08-27 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0028_alter_image_image_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 11, 14, 29, 469643, tzinfo=datetime.timezone.utc)),
        ),
    ]
