# Generated by Django 5.0.2 on 2024-08-27 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0029_alter_subscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 11, 16, 14, 622338, tzinfo=datetime.timezone.utc)),
        ),
    ]
